sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#GCP storage
gcp:
  credentials:
    file: C:/WorkSpace/sky-take-out/sky-server/config/gcp-storage-dev.json
  bucket:
    name: example-bucket1207